/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTerrainAnalysisRouteImport } from './routes/_app.terrain-analysis'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoverNavigationRouteImport } from './routes/_app.rover-navigation'
import { Route as AppResourceEstimationRouteImport } from './routes/_app.resource-estimation'
import { Route as AppRadarAnalysisRouteImport } from './routes/_app.radar-analysis'
import { Route as AppPreprocessingRouteImport } from './routes/_app.preprocessing'
import { Route as AppNewMissionRouteImport } from './routes/_app.new-mission'
import { Route as AppMissionSimulationRouteImport } from './routes/_app.mission-simulation'
import { Route as AppMissionReportRouteImport } from './routes/_app.mission-report'
import { Route as AppMissionManagerRouteImport } from './routes/_app.mission-manager'
import { Route as AppLandingOptimizationRouteImport } from './routes/_app.landing-optimization'
import { Route as AppDatasetManagerRouteImport } from './routes/_app.dataset-manager'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTerrainAnalysisRoute = AppTerrainAnalysisRouteImport.update({
  id: '/terrain-analysis',
  path: '/terrain-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoverNavigationRoute = AppRoverNavigationRouteImport.update({
  id: '/rover-navigation',
  path: '/rover-navigation',
  getParentRoute: () => AppRoute,
} as any)
const AppResourceEstimationRoute = AppResourceEstimationRouteImport.update({
  id: '/resource-estimation',
  path: '/resource-estimation',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarAnalysisRoute = AppRadarAnalysisRouteImport.update({
  id: '/radar-analysis',
  path: '/radar-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppPreprocessingRoute = AppPreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => AppRoute,
} as any)
const AppNewMissionRoute = AppNewMissionRouteImport.update({
  id: '/new-mission',
  path: '/new-mission',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionSimulationRoute = AppMissionSimulationRouteImport.update({
  id: '/mission-simulation',
  path: '/mission-simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionReportRoute = AppMissionReportRouteImport.update({
  id: '/mission-report',
  path: '/mission-report',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionManagerRoute = AppMissionManagerRouteImport.update({
  id: '/mission-manager',
  path: '/mission-manager',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingOptimizationRoute = AppLandingOptimizationRouteImport.update({
  id: '/landing-optimization',
  path: '/landing-optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetManagerRoute = AppDatasetManagerRouteImport.update({
  id: '/dataset-manager',
  path: '/dataset-manager',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dataset-manager': typeof AppDatasetManagerRoute
  '/landing-optimization': typeof AppLandingOptimizationRoute
  '/mission-manager': typeof AppMissionManagerRoute
  '/mission-report': typeof AppMissionReportRoute
  '/mission-simulation': typeof AppMissionSimulationRoute
  '/new-mission': typeof AppNewMissionRoute
  '/preprocessing': typeof AppPreprocessingRoute
  '/radar-analysis': typeof AppRadarAnalysisRoute
  '/resource-estimation': typeof AppResourceEstimationRoute
  '/rover-navigation': typeof AppRoverNavigationRoute
  '/settings': typeof AppSettingsRoute
  '/terrain-analysis': typeof AppTerrainAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dataset-manager': typeof AppDatasetManagerRoute
  '/landing-optimization': typeof AppLandingOptimizationRoute
  '/mission-manager': typeof AppMissionManagerRoute
  '/mission-report': typeof AppMissionReportRoute
  '/mission-simulation': typeof AppMissionSimulationRoute
  '/new-mission': typeof AppNewMissionRoute
  '/preprocessing': typeof AppPreprocessingRoute
  '/radar-analysis': typeof AppRadarAnalysisRoute
  '/resource-estimation': typeof AppResourceEstimationRoute
  '/rover-navigation': typeof AppRoverNavigationRoute
  '/settings': typeof AppSettingsRoute
  '/terrain-analysis': typeof AppTerrainAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dataset-manager': typeof AppDatasetManagerRoute
  '/_app/landing-optimization': typeof AppLandingOptimizationRoute
  '/_app/mission-manager': typeof AppMissionManagerRoute
  '/_app/mission-report': typeof AppMissionReportRoute
  '/_app/mission-simulation': typeof AppMissionSimulationRoute
  '/_app/new-mission': typeof AppNewMissionRoute
  '/_app/preprocessing': typeof AppPreprocessingRoute
  '/_app/radar-analysis': typeof AppRadarAnalysisRoute
  '/_app/resource-estimation': typeof AppResourceEstimationRoute
  '/_app/rover-navigation': typeof AppRoverNavigationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/terrain-analysis': typeof AppTerrainAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/dataset-manager'
    | '/landing-optimization'
    | '/mission-manager'
    | '/mission-report'
    | '/mission-simulation'
    | '/new-mission'
    | '/preprocessing'
    | '/radar-analysis'
    | '/resource-estimation'
    | '/rover-navigation'
    | '/settings'
    | '/terrain-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/dataset-manager'
    | '/landing-optimization'
    | '/mission-manager'
    | '/mission-report'
    | '/mission-simulation'
    | '/new-mission'
    | '/preprocessing'
    | '/radar-analysis'
    | '/resource-estimation'
    | '/rover-navigation'
    | '/settings'
    | '/terrain-analysis'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/dataset-manager'
    | '/_app/landing-optimization'
    | '/_app/mission-manager'
    | '/_app/mission-report'
    | '/_app/mission-simulation'
    | '/_app/new-mission'
    | '/_app/preprocessing'
    | '/_app/radar-analysis'
    | '/_app/resource-estimation'
    | '/_app/rover-navigation'
    | '/_app/settings'
    | '/_app/terrain-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/terrain-analysis': {
      id: '/_app/terrain-analysis'
      path: '/terrain-analysis'
      fullPath: '/terrain-analysis'
      preLoaderRoute: typeof AppTerrainAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rover-navigation': {
      id: '/_app/rover-navigation'
      path: '/rover-navigation'
      fullPath: '/rover-navigation'
      preLoaderRoute: typeof AppRoverNavigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resource-estimation': {
      id: '/_app/resource-estimation'
      path: '/resource-estimation'
      fullPath: '/resource-estimation'
      preLoaderRoute: typeof AppResourceEstimationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radar-analysis': {
      id: '/_app/radar-analysis'
      path: '/radar-analysis'
      fullPath: '/radar-analysis'
      preLoaderRoute: typeof AppRadarAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preprocessing': {
      id: '/_app/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof AppPreprocessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-mission': {
      id: '/_app/new-mission'
      path: '/new-mission'
      fullPath: '/new-mission'
      preLoaderRoute: typeof AppNewMissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission-simulation': {
      id: '/_app/mission-simulation'
      path: '/mission-simulation'
      fullPath: '/mission-simulation'
      preLoaderRoute: typeof AppMissionSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission-report': {
      id: '/_app/mission-report'
      path: '/mission-report'
      fullPath: '/mission-report'
      preLoaderRoute: typeof AppMissionReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission-manager': {
      id: '/_app/mission-manager'
      path: '/mission-manager'
      fullPath: '/mission-manager'
      preLoaderRoute: typeof AppMissionManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/landing-optimization': {
      id: '/_app/landing-optimization'
      path: '/landing-optimization'
      fullPath: '/landing-optimization'
      preLoaderRoute: typeof AppLandingOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dataset-manager': {
      id: '/_app/dataset-manager'
      path: '/dataset-manager'
      fullPath: '/dataset-manager'
      preLoaderRoute: typeof AppDatasetManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetManagerRoute: typeof AppDatasetManagerRoute
  AppLandingOptimizationRoute: typeof AppLandingOptimizationRoute
  AppMissionManagerRoute: typeof AppMissionManagerRoute
  AppMissionReportRoute: typeof AppMissionReportRoute
  AppMissionSimulationRoute: typeof AppMissionSimulationRoute
  AppNewMissionRoute: typeof AppNewMissionRoute
  AppPreprocessingRoute: typeof AppPreprocessingRoute
  AppRadarAnalysisRoute: typeof AppRadarAnalysisRoute
  AppResourceEstimationRoute: typeof AppResourceEstimationRoute
  AppRoverNavigationRoute: typeof AppRoverNavigationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTerrainAnalysisRoute: typeof AppTerrainAnalysisRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetManagerRoute: AppDatasetManagerRoute,
  AppLandingOptimizationRoute: AppLandingOptimizationRoute,
  AppMissionManagerRoute: AppMissionManagerRoute,
  AppMissionReportRoute: AppMissionReportRoute,
  AppMissionSimulationRoute: AppMissionSimulationRoute,
  AppNewMissionRoute: AppNewMissionRoute,
  AppPreprocessingRoute: AppPreprocessingRoute,
  AppRadarAnalysisRoute: AppRadarAnalysisRoute,
  AppResourceEstimationRoute: AppResourceEstimationRoute,
  AppRoverNavigationRoute: AppRoverNavigationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTerrainAnalysisRoute: AppTerrainAnalysisRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
